services:
  client:
    build: ./client
    container_name: client
    tty: true
    stdin_open: true
    depends_on:
      - multiply
      - aggregator
    healthcheck:
      test: ["CMD", "curl", "-f", "http://multiply:15002"]
      interval: 10s
      retries: 5
      start_period: 15s
    networks:
      - matrix_network


  multiply:
    build: ./multiply
    container_name: multiply
    ports:
      - "16002:15002"  # Map to a different port on the host
      - "16003:15003"
      - "16004:15004"
      - "16005:15005"
      - "16006:15006"
    networks:
      - matrix_network

  aggregator:
    build: ./aggregator
    container_name: aggregator
    ports:
      - "16012:15012"  # Map to a different port on the host
    networks:
      - matrix_network

networks:
  matrix_network:
    driver: bridge
    name: matrix_network  # This forces Docker to use this name